import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { Htag } from "@/components";
import GithubIcon from "./github.svg";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={openSans.className}>
        <div className="header">
          <Htag tag="h1">.my_blog</Htag>
          <GithubIcon />
        </div>
        {children}
      </body>
    </html>
  );
}
